#Diccionario de los Datos TITANIC:

```
survival:	Survival	{0 = No, 1 = Yes}
pclass:	Ticket class	{1 = 1st, 2 = 2nd, 3 = 3rd}
sex:	Sex
Age:	Age in years
sibsp:	Number of siblings / spouses aboard the Titanic (hermanos/cónyuges)
parch:	Number of parents / children aboard the Titanic (padres / hijos)
ticket:	Ticket number
fare:	Passenger fare
cabin:	Cabin number
embarked:	Port of Embarkation	{C = Cherbourg, Q = Queenstown, S = Southampton}

```

In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

Ejercicio 1. Carga el conjunto de datos "Titanic" de Seaborn. Calcula la media, mediana y moda de las edades de los pasajeros a bordo.

In [2]:
df = sns.load_dataset('titanic')

In [8]:
df.head(100)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
97,1,1,male,23.0,0,1,63.3583,C,First,man,True,D,Cherbourg,yes,False
98,1,2,female,34.0,0,1,23.0000,S,Second,woman,False,NaN,Southampton,yes,False
99,0,2,male,34.0,1,0,26.0000,S,Second,man,True,NaN,Southampton,no,False

In [7]:
df.count()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [9]:
media = df['age'].mean()
mediana = df['age'].median()
moda = df['age'].mode()
print(f'Media: {media}, Mediana: {mediana}, Moda: {moda}')

Media: 29.69911764705882, Mediana: 28.0, Moda: 0    24.0
Name: age, dtype: float64

In [15]:
df['age'].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: age, dtype: float64

In [19]:
df.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [20]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

Ejercicio 2. Calcula la media y la desviación estándar de las tarifas pagadas por los pasajeros en cada clase (primera, segunda y tercera)

In [24]:
df.groupby('class')['fare'].agg(['mean', 'std', 'count'])

<ipython-input-24-cbed6fd27460>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('class')['fare'].agg(['mean', 'std', 'count'])

             mean        std  count
class
First   84.154687  78.380373    216
Second  20.662183  13.417399    184
Third   13.675550  11.778142    491

Ejercicio 3. Arma un histograma para visualizar la distribución de las edades de los pasajeros.

Ejercicio 4. Crea un boxplot (diagrama de caja) de las tarifas pagadas por los pasajeros en función del puerto de embarque (C = Cherbourg, Q = Queenstown, S = Southampton)

Ejercicio 5. Calcula los percentiles 25, 50 y 75 de las edades de los pasajeros.

Ejercicio 6. Calcula la proporción de pasajeros que sobrevivieron y fallecieron en función de su sexo

Ejercicio 7. Calcula la media de las tarifas pagadas por los pasajeros en cada clase y separada por sexo

Ejercicio 8. Calcula la media y la desviación estándar de las tarifas pagadas por los pasajeros en cada clase (primera, segunda y tercera) y separada por grupos de edades (niños, adultos y ancianos).

Ejercicio 9. Calcula la proporción de pasajeros que sobrevivieron y fallecieron en función de su clase y el puerto de embarque.

Ejercicio 10. Calcula la media y la desviación estándar de las edades de los pasajeros agrupados por el tamaño de sus familias (solos, pequeñas familias y grandes familias).